### ISSUE TITLE
maybe a simpler way

### ISSUE THREAD

**Issue by shenwei356** [stephenturner/mergelanes#1]
`cut` is used to split `id1_L001_R1_001.fastq.gz` by `_` to get the sample ID.

```
ls *R1* | cut -d _ -f 1 | sort | uniq \
    | while read id; do \
        cat $id*R1*.fastq.gz > $id.R1.fastq.gz;
        cat $id*R2*.fastq.gz > $id.R2.fastq.gz;
      done
```

**Comment by stephenturner** [comment]
thanks added suggestion to README in 2c6e0f95e093cbe8fd244f5f25ff3f8380438818 #2

**Comment by IshaMonga** [comment]
It's not working accurately for sample IDs like "A11_Barcodexxx_S11_L001_R1_001". It cat together all L001 pertaining to sample ID A11 with different barcodes also
